### ISSUE TITLE
Docs: Feedback for Discovering Java Clients

### ISSUE THREAD

**Issue by hedshogg** [hazelcast/hz-docs#771]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/clusters/pages/discovering-native-clients.adoc)

The yaml example doesn't match the JSON schema. The example shows that `hazelcast.network.join.discovery-strategies` contains a single `discovery-strategy` child, but according to the [schema](https://hazelcast.com/schema/config/hazelcast-config-5.3.json), the parent `discovery-strategies` is an object containing `discovery-strategies` which is itself an array. This corresponds to:

```yaml
hazelcast:
  properties:
    hazelcast.discovery.enabled: true
  network:
    join:
      discovery-strategies:
        discovery-strategies:
          - enabled: true
            class: com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy
            properties:
              group: 224.2.2.3
              port: 54327
```
